#!/bin/bash
# Configure wmii
wmiiscript=wmiirc # For wmii.sh
. wmii.sh


# Configuration Variables
MODKEY=Mod4
UP=k
DOWN=j
LEFT=h
RIGHT=l

# Bars
noticetimeout=5
noticebar=/rbar/!notice

# Colors tuples: "<text> <background> <border>"
export WMII_NORMCOLORS='#7F7F7F #000000 #81654f'
export WMII_NORMCOLORS='#FFFFFF #000000 #81654f'
export WMII_FOCUSCOLORS='#7F7F7F #000000 #470002'
export WMII_FOCUSCOLORS='#7F7F7F #000000 #BB0006'

export WMII_BACKGROUND='#333333'
export WMII_FONT='-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'

set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)
export WMII_TERM="st -e screen"

if ! test -d "${WMII_CONFPATH%%:*}"; then
    mkdir "${WMII_CONFPATH%%:*}"
    res=$(wihack -type DIALOG xmessage -nearmouse -buttons Windows,Alt -print -fn $WMII_FONT \
          "Welcome to wmii,$wi_newline$wi_newline" \
          "Most of wmii's default key bindings make use of the$wi_newline" \
          "Windows key, or equivalent. For keyboards lacking such$wi_newline" \
          "a key, many users change this to the Alt key.$wi_newline$wi_newline" \
          "Which would you prefer?")
    [ "$res" = "Alt" ] && MODKEY=Mod4
    echo "MODKEY=$MODKEY" >"${WMII_CONFPATH%%:*}/wmiirc_local"
    chmod +x "${WMII_CONFPATH%%:*}/wmiirc_local"
fi

# Menu history
hist="${WMII_CONFPATH%%:*}/history"
histnum=5000

# Column Rules
wmiir write /colrules <<!
/gimp/ -> 17+83+41
/.*/ ->  68+32 # Golden Ratio
# /.*/ -> 62+38 # Golden Ratio
!

# Tagging Rules
# a tilde means that the window will float
wmiir write /tagrules <<!
/MPlayer|VLC/ -> ~
/Spotify.*/ -> +9
!

# Song status info
songStatus() {
    spotify="$(pidof spotify 1>/dev/null; \
        if [ "$?" -gt 0 ]
        then 
            printf " [[ No song playing ]]";
        else
            dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' \
        | awk '
    BEGIN { songName=""; artist="" }
    {
        if(NR==22) { for(i=2; i<NF+1; i++) { artist  =artist" "$i; } }
        if(NR==39) { for(i=3; i<NF+1; i++) { songName=songName" "$i } }
    }
    END { gsub(/"/,"", artist); gsub(/"/,"",songName);
          print artist":"songName }
    ' ; fi)"

    echo -n ${spotify}
}

netStatus()
{
    upRead="${1}"
    downRead="${2}"
    upRead2=$(head /sys/class/net/eth0/statistics/rx_bytes)
    downRead2=$(head /sys/class/net/eth0/statistics/tx_bytes)
    downkBs=$(( (${upRead2} - ${upRead}) / 1024))
    upkBs=$(( (${downRead2} - ${downRead}) / 1024))

    echo -n ${downkBs}'/'${upkBs} kB/s $((upRead2 / 1024 / 1024))/$((downRead2 / 1024 / 1024)) MB \
        '|' $(nm-tool | awk '/eth0/ { print $4; }' )
}

# Status Bar Info
#: Note that the call for this function can be found by searching here
#: for the string "Action status"
status() {
    volume=`amixer sget Master`
    volume="${volume#Simple*\[}"
    volume="${volume%%]*]}"
    memstat="$(awk '
    BEGIN { swap=0; total=0; avail=0; cacheMem }
    {
        if     (NR == 1) { total=int($2 / 1024); }
        else if(NR == 2) { avail=int($2 / 1024); }
        else if(NR == 5) { cacheMem=int($2 / 1024); }
        else if(NR == 6) { swap=int($2 / 1024); }
    }
    END { print cacheMem":"(total-avail)"/"total" MB | "swap" MB" }' \
        /proc/meminfo)"

    topProc=$(ps --user ${USER} hS -o pcpu:4,time,comm:20 --sort=-pcpu | head --lines=1)

    echo -n ${topProc} \
        '|' $(awk ' { if($1>100) { print "100%"; } else { printf("%3d\%", $1); } } ' /sys/class/power_supply/BAT0/capacity) \
        '|' ${memstat} \
        '|' $(awk ' { gsub(".*/", "", $4); print $1, $2, $3, $4 } ' /proc/loadavg) \
        '|' "${volume:-amixer error}" \
        '|' $(date +%a\ %b\ %d\ \(%H\)"$(TZ="America/Lima" date +%H)":%M:%S\ %Y);
        # '|' $(date '+%c');
}

local_events() { true;}
wi_runconf -s wmiirc_local

echo $WMII_NORMCOLORS | wmiir create $noticebar

# Event processing
events() {
    cat <<'!'
# Events
Event CreateTag
    echo "$WMII_NORMCOLORS" "$@" | wmiir create "/lbar/$@"
Event DestroyTag
    wmiir remove "/lbar/$@"
Event FocusTag
    wmiir xwrite "/lbar/$@" "$WMII_FOCUSCOLORS" "$@"
Event UnfocusTag
    wmiir xwrite "/lbar/$@" "$WMII_NORMCOLORS" "$@"
Event UrgentTag
    shift
    wmiir xwrite "/lbar/$@" "*$@"
Event NotUrgentTag
    shift
    wmiir xwrite "/lbar/$@" "$@"
Event LeftBarClick LeftBarDND
    shift
    wmiir xwrite /ctl view "$@"
Event Unresponsive
    {
        client=$1; shift
        msg="The following client is not responding. What would you like to do?$wi_newline"
        resp=$(wihack -transient $client \
                  xmessage -nearmouse -buttons Kill,Wait -print
                  -fn "${WMII_FONT%%,*}" "$msg $(wmiir read /client/sel/label)")
        if [ "$resp" = Kill ]; then
            wmiir xwrite /client/$client/ctl slay &
        fi
    }&
Event Notice
    wmiir xwrite $noticebar $wi_arg

    kill $xpid 2>/dev/null # Let's hope this isn't reused...
    { sleep $noticetimeout; wmiir xwrite $noticebar ' '; }&
    xpid = $!

# Menus
Menu Client-3-Delete
    wmiir xwrite /client/$1/ctl kill
Menu Client-3-Kill
    wmiir xwrite /client/$1/ctl slay
Menu Client-3-Fullscreen
    wmiir xwrite /client/$1/ctl Fullscreen on
Event ClientMouseDown
    wi_fnmenu Client $2 $1 &

Menu LBar-3-Delete
    tag=$1; clients=$(wmiir read "/tag/$tag/index" | awk '/[^#]/{print $2}')
    for c in $clients; do
        if [ "$tag" = "$(wmiir read /client/$c/tags)" ]; then
            wmiir xwrite /client/$c/ctl kill
        else
            wmiir xwrite /client/$c/tags -$tag
        fi
        if [ "$tag" = "$(wi_seltag)" ]; then
            newtag=$(wi_tags | awk -v't='$tag '
                $1 == t { if(!l) getline l
                      print l
                      exit }
                { l = $0 }')
            wmiir xwrite /ctl view $newtag
        fi
    done
Event LeftBarMouseDown
    wi_fnmenu LBar "$@" &

# Actions
Action showkeys
    echo "$KeysHelp" | xmessage -file - -fn ${WMII_FONT%%,*}
Action quit
    wmiir xwrite /ctl quit
Action exec
    wmiir xwrite /ctl exec "$@"
Action rehash
    wi_proglist $PATH >$progsfile
Action status
    set +xv
    if wmiir remove /rbar/status 2>/dev/null; then
        sleep 2
    fi
    echo "$WMII_NORMCOLORS" | wmiir create /rbar/status
    while status | wmiir write /rbar/status; do
        sleep 1
    done
Action netStatus
    set +xv
    if wmiir remove /rbar/netStatus 2>/dev/null; then
        sleep 2
    fi
    echo "$WMII_NORMCOLORS" | wmiir create /rbar/netStatus
    upRead=0
    downRead=0
    while netStatus ${upRead} ${downRead} | wmiir write /rbar/netStatus ; do
        upRead=$(head /sys/class/net/eth0/statistics/rx_bytes)
        downRead=$(head /sys/class/net/eth0/statistics/tx_bytes)
        sleep 1
    done
Action songStatus
    set +xv
    if wmiir remove /lbar/songStatus 2>/dev/null; then
        sleep 2
    fi
    echo "$WMII_NORMCOLORS" | wmiir create /lbar/songStatus
    while songStatus | wmiir write /lbar/songStatus; do
        sleep 7
    done
# Key Bindings
KeyGroup Moving around
Key $MODKEY-$LEFT   # Select the client to the left
    wmiir xwrite /tag/sel/ctl select left
Key $MODKEY-$RIGHT  # Select the client to the right
    wmiir xwrite /tag/sel/ctl select right
Key $MODKEY-$UP     # Select the client above
    wmiir xwrite /tag/sel/ctl select up
Key $MODKEY-$DOWN   # Select the client below
    wmiir xwrite /tag/sel/ctl select down

Key $MODKEY-Control-$DOWN
        wmiir xwrite /tag/sel/ctl grow sel sel down 5
Key $MODKEY-Control-$UP
        wmiir xwrite /tag/sel/ctl grow sel sel down -5
Key $MODKEY-Control-$LEFT
        wmiir xwrite /tag/sel/ctl grow sel sel right -5
Key $MODKEY-Control-$RIGHT
        wmiir xwrite /tag/sel/ctl grow sel sel right 5

# Move and activate vnc instance (provided it is center left ish on monitor)
Key $MODKEY-o
    wmctrl -a TightVNC && xdotool mousemove 9999 9999 && xdotool mousemove 1000 500


Key $MODKEY-space   # Toggle between floating and managed layers
    wmiir xwrite /tag/sel/ctl select toggle

KeyGroup Moving through stacks
# Key $MODKEY-Control-$UP    # Select the stack above
#     wmiir xwrite /tag/sel/ctl select up stack
# Key $MODKEY-Control-$DOWN  # Select the stack below
#     wmiir xwrite /tag/sel/ctl select down stack

KeyGroup Moving clients around
Key $MODKEY-Shift-$LEFT   # Move selected client to the left
    wmiir xwrite /tag/sel/ctl send sel left; 
Key $MODKEY-Shift-$RIGHT  # Move selected client to the right
    wmiir xwrite /tag/sel/ctl send sel right; 
Key $MODKEY-Shift-$UP     # Move selected client up
    wmiir xwrite /tag/sel/ctl send sel up
Key $MODKEY-Shift-$DOWN   # Move selected client down
    wmiir xwrite /tag/sel/ctl send sel down

Key $MODKEY-Shift-space   # Toggle selected client between floating and managed layers
    wmiir xwrite /tag/sel/ctl send sel toggle

KeyGroup Client actions
Key $MODKEY-f # Toggle selected client's fullsceen state
    wmiir xwrite /client/sel/ctl Fullscreen toggle
Key $MODKEY-Shift-c # Close client
    wmiir xwrite /client/sel/ctl kill

KeyGroup Changing column modes
Key $MODKEY-d # Set column to default mode
    wmiir xwrite /tag/sel/ctl colmode sel default-max
Key $MODKEY-s # Set column to stack mode
    wmiir xwrite /tag/sel/ctl colmode sel stack-max
Key $MODKEY-m # Set column to max mode
    wmiir xwrite /tag/sel/ctl colmode sel stack+max

KeyGroup Running programs
Key $MODKEY-a      # Open wmii actions menu
    action $(wi_actions | wimenu -h "${hist}.actions" -n $histnum) &
Key $MODKEY-p      # Open program menu
    setsid "$(compgen -c | dmenu)" &
Key $MODKEY-c       # open chromum
    eval wmiir setsid google-chrome-stable &
Key $MODKEY-u       # open uzbl
    eval wmiir setsid uzbl-browser &
Key $MODKEY-n       # open spotify
    eval wmiir setsid /opt/spotify/spotify-client/spotify &

Key $MODKEY-Return # Launch a terminal
    eval wmiir setsid $WMII_TERM &

KeyGroup Other
Key $MODKEY-Control-t # Toggle all other key bindings
    case $(wmiir read /keys | wc -l | tr -d ' \t\n') in
    0|1)
        echo -n "$Keys" | wmiir write /keys
        wmiir xwrite /ctl grabmod $MODKEY;;
    *)
        wmiir xwrite /keys $MODKEY-Control-t
        wmiir xwrite /ctl grabmod Mod3;;
    esac

KeyGroup Tag actions
Key $MODKEY-t       # Change to another tag
    (tag=$(wi_tags | wimenu -h "${hist}.tags" -n 50) && wmiir xwrite /ctl view $tag) &
Key $MODKEY-Shift-t # Retag the selected client
    c=$(wi_selclient)
    (tag=$(wi_tags | wimenu -h "${hist}.tags" -n 50) && wmiir xwrite /client/$c/tags $tag) &
!
    for i in 0 1 2 3 4 5 6 7 8 9; do
        cat <<!
Key $MODKEY-$i       # Move to the numbered view
    wmiir xwrite /ctl view "$i"
Key $MODKEY-Shift-$i     # Retag selected client with the numbered tag
    wmiir xwrite /client/sel/tags "$i"
!
    done
}
wi_events events local_events

# WM Configuration
wmiir write /ctl <<!
    font $WMII_FONT
    focuscolors $WMII_FOCUSCOLORS
    normcolors $WMII_NORMCOLORS
    grabmod $MODKEY
    border 1
!
# xsetroot -solid "$WMII_BACKGROUND" &
# hsetroot -full "~/.background.jpg" &
feh --bg-scale ~/.background.jpg &

# Misc
progsfile="$(wmiir namespace)/.proglist"
action status &
action netStatus &
action songStatus &
wi_proglist $PATH >$progsfile &

# Setup Tag Bar
IFS="$wi_newline"
wmiir rm $(wmiir ls /lbar | sed 's,^,/lbar/,') >/dev/null
seltag=$(wmiir read /tag/sel/ctl | sed 1q)
unset IFS
wi_tags | while read tag
do
    if [ "$tag" = "$seltag" ]; then
        echo "$WMII_FOCUSCOLORS" "$tag"
    else
        echo "$WMII_NORMCOLORS" "$tag"
    fi | wmiir create "/lbar/$tag"
done

wi_eventloop

