#!/usr/bin/env bash
#: Title        : IsValidIP
#: Date         : 2010-00-00
#: Author       : Anders Sildnes
#: Version      : 1.0
#: Desctiption  : Check a given IP-address if it is valid
#: Options   	: $1 should be the IP to check

isvalidip()
{
  case $1 in
    "" | *[!0-9.]* | *[!0-9]) return 1 ;;
  esac

  local IFS=.

  set -- $1
  
  [ $# -eq 4 ] && [ ${1:-666} -le 255 ] && [ ${2:-666} -le 255 ] && [ ${3:-666} -le 255 ] && [ ${4:-666} -le 255 ]
}
