#!/bin/bash

cd() #@ Change directory, saving location on the directory stack
{
    # TODO: no support for flags (e.g. cd -p)
    # If we have an argument passed to cd
    if [ -n "$1" ]
    then
        # Push directory to the stack
        pushd "${1}"
    else # If no argument was passed to cd
        # Go to home directory
        pushd "${HOME}"
    fi 2>/dev/null # Ignore output

    # If an error occured, pushd didn't work
    if [ $? -ne 0 ]
    then    
        # Let the builtin make an attempt..
        builtin cd "$1" 1&> /dev/null
        if [ $? -ne 0 ]
        then    
            pushd "$(dirname "${1}")"
        fi
        if [ $? -ne 0 ]
        then    
            printf "Could not cd into %s\n" "${1}" > /dev/fd/1
        fi
    fi


#    clear > /dev/fd/0
 #   ls > /dev/fd/0

    return "$?"
} > /dev/null # Supress output

cd "$@"
