#!/usr/bin/env bash

cd() #@ Change directory, saving location on the directory stack
{
    # TODO: no support for flags (e.g. cd -p)
    # If we have an argument passed to cd
    if [ -n "$1" ]
    then
        # Push directory to the stack
        pushd "${1}"
    else # If no argument was passed to cd
        # Go to home directory
        pushd "${HOME}"
    fi 2>/dev/null # Ignore output

    # If an error occured, pushd didn't work
    if [ $? -ne 0 ]
    then    
        # Let the builtin make an attempt..
        builtin cd "$1" 1&> /dev/null
        if [ $? -ne 0 ]
        then    
            pathWithoutFilename="$(dirname "${1}")"
            if [ "." == "${pathWithoutFilename}" ]
            then
                printf "Could not cd into %s\n" "${1}" > /dev/fd/2
            else
                pushd "${pathWithoutFilename}"
            fi
            
        fi
        if [ $? -ne 0 ]
        then    
            printf "Could not cd into %s\n" "${1}" > /dev/fd/1
        fi
    fi

    return "$?"
} > /dev/null # Supress output


# don't run on sourcing
[[ $_ != "$0" ]] || cd "$@" || echo "error happened" >/dev/fd/2
