# test -f /local/skel/all.bashrc && . /local/skel/all.bashrc
# If not running interactively, don't read preferences.
[ -z "$PS1" ] && return

export EIX_LIMIT=0
source /etc/profile.d/bash-completion.sh

# Variables ##
# PS1='\u@\h: ~${PWD##*/} > '
GREEN=$'\e[01;32m'
YELLOW=$'\e[00;33m'
WHITE=$'\e[00;00m'
RED=$'\e[01;31m'
# bash is fun, but annoying: PS1 is eval some strange way, and needs to escape colors
PROMPT_COMMAND=__prompt_command  # Func to gen PS1 after CMDs
function __prompt_command() {
    PS1="`export EXITSTATUS=$?`$(printf "\[${YELLOW}\]%s \[${WHITE}\]%s %s \[${WHITE}\]" \
        "$(date +%k:%S)" \
        "\u@\h: ./${PWD##*/}")"

    local EXIT="$?"             # This needs to be first
    if [ $EXIT = 0 ]; then
        PS1+="${GREEN}:)"      # Add red if exit code non 0
    else
        PS1+="${RED}:("
    fi
    PS1+="${WHITE}\n$ "
}


EDITOR="gvim"
HISTIGNORE="ls:l:clear"
PATH="${PATH}:${HOME}/dotfiles/Bash:$GOROOT/bin:$GOPATH/bin"

export HISTCONTROL="ignoredups"

# Disable Software Flow Control (xon)
# (in practice: give me back Ctrl+s and Ctrl+q)
stty -ixon

# XMonad needs this to run java nicely
export _JAVA_AWT_WM_NONREPARENTING=1

# My jedi-vim needs this(ugh!)
export IPYTHONDIR="~/.ipython"


# It's a lot more annoying to not have an old command in history than having a large file
export HISTSIZE=10000
export HISTFILE_SIZE=10000


# Reload history after each command (needed to share history across shells live)
# export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Append dirname to window title if WMII_IS_RUNNING
WMII_IS_RUNNING=`ps a | grep wmii | awk '/[^"grep"] wmii$/'`
if [ -n "$WMII_IS_RUNNING" ]
then
  PROMPT_COMMAND="${PROMPT_COMMAND} ; dirs | wmiir write /client/sel/label"
fi

export XDG_CONFIG_HOME="~/.local/share"

# If the command-line has an empty entry, don't try to autocomplete with tab
shopt -s no_empty_cmd_completion
# Enable auto cding, so you don't have to use "cd /the/dir" just "/the/dir"
shopt -s autocd
# Enable directory autocorrection
shopt -s cdspell dirspell
# Append history across shells
shopt -s histappend

BASH_INCLUDES_DEST="${HOME}/.bash_includes"
# Check for file and include it
[ -e "${BASH_INCLUDES_DEST}" ] && source "${BASH_INCLUDES_DEST}"

# Get proper auto-completion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
        . /etc/bash_completion
fi

complete -cf sudo
