#!/usr/bin/env bash
#shellcheck disable=SC1091,SC1090

# If not running interactively, don't read preferences.
[ -z "$PS1" ] && return

bind -f "${HOME}/dotfiles/BashRC/inputrc"

# Variables ##
# PS1='\u@\h: ~${PWD##*/} > '
#GREEN=$'\e[01;32m'
YELLOW="$(printf '%b' '\e[00;33m')"
WHITE="$(printf '%b' '\e[00;00m')"
#RED=$'\e[01;31m'
PS1=$(printf "\[${YELLOW}\]%s \[${WHITE}\]%s\n:\[${WHITE}\]\n" \
         "$(date +%k:%M)" \
         "\u@\h: \w")
# PROMPT_COMMAND=__prompt_command  # Func to gen PS1 after CMDs
# function __prompt_command() {
#     local EXIT="$?"
#         "$(date +%k:%M)" \
#         "\u@\h: ./${PWD##*/}")"
#     if [ $EXIT = 0 ]; then
#         PS1+="${GREEN}:)"      # Add red if exit code non 0
#     else
#         PS1+="${RED}:("
#     fi
#     PS1+="${WHITE}\n$ "
# }


export EDITOR="nvim"
export GEM_HOME="${HOME}/.gem"
export GEM_PATH="${HOME}/.gem"
HISTIGNORE="ls:l:clear"
export GOPATH="${HOME}/.go"
PATH="${PATH}:${HOME}/dotfiles/Bash:${GEM_PATH}/bin:$GOROOT/bin:$GOPATH/bin:${HOME}/.cabal/bin:${HOME}/.local/bin"

export HISTCONTROL="ignoreboth:erasedups"

# Disable Software Flow Control (xon)
# (in practice: give me back Ctrl+s and Ctrl+q)
stty -ixon

# XMonad needs this to run java nicely
export _JAVA_AWT_WM_NONREPARENTING=1

export NIX_PATH=peskOverrides=/home/andesil/.nixpkgs:${NIX_PATH}

# My jedi-vim needs this(ugh!)
export IPYTHONDIR="${HOME}/.ipython"

# It's a lot more annoying to not have an old command in history than having a large file
export HISTSIZE=100000
export HISTFILE_SIZE=1000000

# need the if statement for e.g. mac
if [ "${BASH_VERSINFO[0]}" -ge 4 ] 
then
    shopt -s autocd 
    shopt -s histappend
fi

# Enable directory autocorrection
shopt -s cdspell 

. "${HOME}/dotfiles/BashRC/bash_aliases"
for file in ${HOME}/dotfiles/Bash/Sourced/* ; do . "${file}"; done

# complete -cf sudo

[ -f ~/.fzf.bash ] && . ~/.fzf.bash
export SCIPY_PIL_IMAGE_VIEWER=xdg-open
export XDG_CONFIG_HOME="${HOME}/.config/"
export XDG_DATA_DIR="${HOME}/.local/share/"
export XDG_DATA_HOME="${HOME}/.local/share/"
export FZF_DEFAULT_OPTS='--extended -i --exact'
export FZF_COMPLETION_OPTS='--extended --exact'

if command -v brew
then
    # brew install bash-completion bash-git-prompt
    . "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
    . "$(brew --prefix)/etc/bash_completion"
    if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
        . "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
    fi
else
    [ -e "${HOME}/.bash-git-prompt/gitprompt.sh" ] && . "${HOME}/.bash-git-prompt/gitprompt.sh"
    # Get proper auto-completion
    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
        . /etc/bash_completion
    fi

fi
# Set config variables first
export GIT_PROMPT_ONLY_IN_REPO=1

[ -d "${HOME}/defaultenv3" ] &&  . "${HOME}/defaultenv3/bin/activate"

[ -n "$NVIM_LISTEN_ADDRESS" ] && alias :='~/.nvimex.py'


# added by travis gem
[ -f /home/andesil/.travis/travis.sh ] && . /home/andesil/.travis/travis.sh
