#!/bin/bash

# Misc
alias annoying="find -type f -print0 | grep --color=never -Ez '[^/]{5}$' | xargs -0 "

# Commonly used flags
alias ls='ls --color=auto --human-readable --classify -C'
alias lt='ls --sort=time --reverse'
alias la='ls -A'
alias ll='ls -al'
alias l='ls'

alias df="df --human-readable"
alias du="du --human-readable"
alias free="free --human"

alias bc='bc --mathlib --quiet'

alias mv='mv --verbose --interactive'
alias rmdir='rmdir --verbose'
alias mkdir='mkdir --verbose'

alias gdb="gdb --quiet"
alias grep="grep --color=always"

# Commonly used lazyness
alias check="aspell check -d en_US"
alias checkNO="aspell check -d no"
alias gacp="git add . && git commit -m \"\$(fortune | tr '\n' ' ')\" && git push" # for private repos, I do not care what the commit message is
alias eix="dnf search"
alias emerge="sudo dnf install -y"
alias fb="fbcmd notices | head ; fbcmd inbox | head"
alias m="make"
alias no="setxkbmap no"
alias paste="xclip -o && echo"
alias pg="ps aux | grep "
alias py="ipython"
alias upd="sudo emerge -uDN @world"
alias us="setxkbmap us"

# Commonly used folders
alias www='cd /var/www/'
alias pf='cd "/home/andesil/Homework/TDT4260/"'
alias nerd='cd /home/andesil/Homework/Misc/NerdWars/'
alias ct='cd /home/andesil/Homework/TDT4205/ex4'
alias bd='cd /home/andesil/Homework/TDT4305/'

function smallimg()
{
    convert -size 32x32 "xc:${2:-orange}" "${1:-empty.jpg}"
}


export OTHER_COMP="169.254.244.132"
function samba()
{
    # if [ ! -d samba/${2} ]
    # then
    #     mkdir -vp samba/${2}
    # fi
    # GID=$(id -g ${USER})
    # sudo   mount -t cifs //${1}/${2:obteam2} samba/${2}/ -o user=asildnes,domain=SYSCOPERU,gid=${GID},uid=${UID}
    # # sudo   mount -t cifs //${1}/${2:obteam2} samba/${2}/ -o user=asildnes,domain=SYSCOPERU,noperm,rw
    if [ ! -d "samba/${1}" ]
    then
        mkdir -vp samba/"${1}"
    fi
    GID=$(id -g "${USER}")
    sudo   mount -t cifs "//${OTHER_COMP}/${1:obteam2}" "${HOME}/samba/${1}/" -o user=asildnes,domain=SYSCOPERU,gid="${GID}",uid="${UID}"
    # sudo   mount -t cifs //${1}/${2:obteam2} samba/${2}/ -o user=asildnes,domain=SYSCOPERU,noperm,rw
}

function murder()
{
    # shellcheck disable=SC2046
    kill -9 $(ps aux | awk "!/grep.*${1}/ && /${1}/ {print \$2}")
}

alias stream="vlc   --sout-display-delay=30000 --sout-transcode-venc=mp4 v4l2:///dev/video0"
alias gclean='git gc --prune=now  ; git remote prune origin'
