#!/bin/bash

BASH_ALIASES="${HOME}/.bash_aliases"
# Check for bash_aliases and include it
[ -e "${BASH_ALIASES}" ] && source "${BASH_ALIASES}"

# Make use of our .dircolors
eval `dircolors --bourne-shell ~/.dircolors`

for file in ${HOME}/dotfiles/Bash/Sourced/* ; do source ${file}; done

# EOF
