#!/usr/bin/env bash

git status --porcelain  | cut -d$' ' -f3 | sed '/^$/d'
echo "Cleaning in 3 secs..."
sleep 1
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 0

for file in $(git status --porcelain  | cut -d$' ' -f3 | sed '/^$/d'); do git reset HEAD $file ; done
