#!/bin/bash

IFS=$'\n' # read lines separated by newline
sepChar="${1:-=}" # the character to align around

# Read the data
inData=""
while read -r input
do
    inData="$(printf "%s\n%s" "${inData}" "${input}")"
done

outfile="/tmp/sqlOutput.txt"

tsql -S mywin -U sysco-estate -P Ddgwv7236 -o quiet <<<"${inData}
GO

" > ${outfile}  2>/dev/null

gvim ${outfile}

printf "%s" "${inData:okaaay}"

# EOF

