#!/bin/bash

# ~/.cache/neobundle/syntastic/syntax_checkers/cs/mcs.vim 
# let makeprg = self.makeprgBuild({ 'exe': 'xbuild', 'args_after': system('~/dotfiles/Bash/mcsCompile ' .expand('%:p') )})
# ~/.vim/rc/plugins.rc.vim
# let g:syntastic_checkers = ['mcs']

test -z ${1} && exit
filename="${1}"
dirname="${filename%/*}"

test -z $(git root)

echo /property:GenerateFullPaths=true /v:q /p:Configuration=Debug ${dirname}/*.csproj 
