#!/bin/bash

# filename="Integration_Webmegler_IntegrationTests/Test.cs"

# ~/.cache/neobundle/syntastic/syntax_checkers/cs/mcs.vim 
#
# let makeprg = self.makeprgBuild({ 'args_after': system('~/dotfiles/Bash/mcsCompile ' .expand('%:p') )})
#
#

test -z ${1} && exit
filename="${1}"
dirname="${filename%%/*}/bin/Debug/"

test -z $(git root)

grep "using" --color=none ${filename} | \
    awk 'BEGIN{i=1;printf " --parse -warn:0 " ;}  
    { 
         if ($0 ~ /System/) { arr[i++] = $2; }
         else { arr[i++] = "'${dirname}'"$2".dll"; }
    }

    END { 
        for(x=1;x<i;x++) { 
            gsub(";","",arr[x]); printf "/reference:%s ", arr[x];
        } printf "\n" }
    ' 
