#!/usr/bin/env bash

if [ -z "${1}" ]
then
    echo "usage: p <process name>" > /dev/fd/2
    exit 1
fi

# grep in the end is to filter out the bash shell invoked for this script
pgrep -u "${USER}" --list-name --ignore-case --full "${1}" | grep -v $$
