#!/usr/bin/env bash
# shellcheck disable=SC1091

# "pdf" is just a function to open up a pdf, it can be replaced by
# "setsid evince ${file}" or similar
source /home/andesil/dotfiles/Bash/pdf

pdfautoopen()
{
    local watchedFolder
    watchedFolder="${HOME}/Downloads/"
    while out="$(inotifywait  -e create "${watchedFolder}")"
    do 
        file="$(ls -t -r -1 "${watchedFolder}" | tail -n1)"
        [[ "${out}" == *"chromium"* ]] || [[ "${file}" == *".crdownload" ]] \
            && continue

        filetype="$(xdg-mime query filetype "${watchedFolder}${file}")"
        if [ "${filetype}" = "application/pdf" ]
        then 
            pdf "${watchedFolder}${file}"
        elif [ "${filetype}" = "application/zip" ]
        then
            mkdir "${watchedFolder}${file}EXTRACTED"
            unzip "${watchedFolder}${file}" -d "${watchedFolder}${file}EXTRACTED"
        fi
    done
} #2> /dev/null

pdfautoopen
