#!/usr/bin/env bash
# Load all files from a commit into a tab in vim
# .. and compare it with its previous commit 
# essentially, do `git show` in vim

set -xe

commit="${1:-HEAD}"
commitFiles=$(git diff-tree --no-commit-id --name-only -r "$commit")
git --no-pager show --stat "${commit}" > /tmp/viewcommit
vim -p ${commitFiles} /tmp/viewcommit -c "tabdo silent if exists(\":Gdiff\") | :Gedit $1:% | :Gdiff ~1 | endif" 
